---
- name: Install ngix
  hosts: dev
  become: true


  tasks:
  - name: install the ngix
    apt:
      name: nginx
      state: present

  - name: start nginx
    service:
      name: nginx
      state: started
